# Generated by Django 5.1 on 2024-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_activation_code_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
