# Generated by Django 5.1 on 2024-08-08 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_reset_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('text', models.CharField(max_length=255)),
                ('image_120x120', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('image_400x400', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('image_800x800', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
