# Generated by Django 5.1 on 2024-08-08 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_post_order_post_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_120x120',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_400x400',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_800x800',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_120x120', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('image_400x400', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('image_800x800', models.ImageField(blank=True, null=True, upload_to='uploads/resized/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.post')),
            ],
        ),
    ]
